export type {
  WorkspaceAnchor,
  WorkspaceHeadDrift,
  WorkspaceFilesDrift,
  WorkspaceRepositoryDrift,
  WorkspaceDrift,
  VerifyResult,
  ForkOk,
  ForkChangedAnchor,
  ForkExists,
  ForkIncomplete,
  ForkUnleased,
  ForkNoRevision,
  ForkInvalidChild,
  ForkResult,
  LeaseClaimed,
  LeaseHeld,
  LeaseIncomplete,
  AcquireResult,
  WorkspaceReleaseResult,
  RecoverResult,
  WorkspaceProvider,
} from '@obversa/api';
export type { GitWorkspaceSnapshot } from '../core/git.js';
